# SPDX-FileCopyrightText: Copyright (c) 2020-2022 Polystat.org
# SPDX-License-Identifier: MIT

[files]
extend-exclude = [
  "white-paper/main.bib",
]

[default.extend-words]
inex = "inex"
elipse = "elipse"
