# SPDX-FileCopyrightText: Copyright (c) 2020-2022 Polystat.org
# SPDX-License-Identifier: MIT

version = 1
[[annotations]]
path = [
    ".gitattributes",
    ".gitignore",
    ".pdd",
    "**/.gitignore",
    "**/*.eo",
    "**/*.json",
    "**/*.md",
    "**/*.pdf",
    "**/*.txt",
    "white-paper/.latexmkrc",
    "white-paper/.texsc",
    "white-paper/aspell.en.pws",
    "white-paper/main.bib",
    "white-paper/wp.tex",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2020-2022 Polystat.org"
SPDX-License-Identifier = "MIT"
