# SPDX-FileCopyrightText: Copyright (c) 2020-2022 Polystat.org
# SPDX-License-Identifier: MIT
name: latexmk
on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: yegor256/latexmk-action@0.20.0
        with:
          path: white-paper
          opts: -pdf
          packages: anyfontsize biblatex caption catchfile changepage currfile datetime enumitem environ fancyhdr ffcode filehook float fmtcount fontsize footmisc framed fvextra geometry href-ul huawei hyperref iexec koma-script lastpage libertine listings listingsutf8 makecell microtype pagecolor paralist pdfcol pgf pgfopts ragged2e setspace svg tcolorbox textpos tikzfill titlesec titling transparent trimspaces upquote wrapfig xcolor xstring
      - run: mkdir white-paper/pdf
      - run: cp white-paper/wp.pdf white-paper/pdf
      - uses: JamesIves/github-pages-deploy-action@v4.9.0
        with:
          branch: gh-pages
          folder: white-paper/pdf
          clean: false
